#!/usr/bin/env tsx
/**
 * BDRclaw Setup Wizard
 * Interactive terminal setup for first-time configuration.
 *
 * Usage: npm run wizard
 *
 * What it does:
 *   1. Checks prerequisites (Node, Docker/Apple Container, Anthropic API key)
 *   2. Collects company + ICP info
 *   3. Configures email accounts (Gmail / Outlook)
 *   4. Configures LinkedIn accounts
 *   5. Configures CRM (optional)
 *   6. Writes .env file
 *   7. Initializes databases + directory structure
 *   8. Seeds the first account in SQLite
 */

import { execSync, spawnSync } from 'child_process';
import fs from 'fs';
import path from 'path';
import readline from 'readline';
import { fileURLToPath } from 'url';

// ── ANSI colors ───────────────────────────────────────────────────────────────

const C = {
  reset:   '\x1b[0m',
  bold:    '\x1b[1m',
  dim:     '\x1b[2m',
  blue:    '\x1b[34m',
  cyan:    '\x1b[96m',
  green:   '\x1b[32m',
  yellow:  '\x1b[33m',
  red:     '\x1b[31m',
  magenta: '\x1b[35m',
  white:   '\x1b[97m',
  bgBlue:  '\x1b[44m',
  muted:   '\x1b[90m',
};

const b = (s: string) => `${C.bold}${s}${C.reset}`;
const c = (s: string) => `${C.cyan}${s}${C.reset}`;
const g = (s: string) => `${C.green}${s}${C.reset}`;
const r = (s: string) => `${C.red}${s}${C.reset}`;
const y = (s: string) => `${C.yellow}${s}${C.reset}`;
const m = (s: string) => `${C.muted}${s}${C.reset}`;

// ── Readline helpers ──────────────────────────────────────────────────────────

const rl = readline.createInterface({ input: process.stdin, output: process.stdout });

function ask(question: string): Promise<string> {
  return new Promise((resolve) => rl.question(question, (answer) => resolve(answer.trim())));
}

async function confirm(question: string, defaultYes = true): Promise<boolean> {
  const hint = defaultYes ? '[Y/n]' : '[y/N]';
  const answer = await ask(`${question} ${m(hint)} `);
  if (answer === '') return defaultYes;
  return answer.toLowerCase().startsWith('y');
}

function print(msg = ''): void {
  console.log(msg);
}

function nl(): void {
  print();
}

function section(title: string): void {
  nl();
  print(`${C.bold}${C.blue}── ${title} ${'─'.repeat(Math.max(0, 50 - title.length))}${C.reset}`);
  nl();
}

function ok(msg: string): void {
  print(`  ${g('✓')} ${msg}`);
}

function warn(msg: string): void {
  print(`  ${y('⚠')} ${msg}`);
}

function fail(msg: string): void {
  print(`  ${r('✗')} ${msg}`);
}

function info(msg: string): void {
  print(`  ${m('·')} ${msg}`);
}

// ── Environment check ─────────────────────────────────────────────────────────

function checkCommand(cmd: string): boolean {
  try {
    execSync(`which ${cmd}`, { stdio: 'ignore' });
    return true;
  } catch {
    return false;
  }
}

function nodeVersion(): string {
  return process.version;
}

function checkPrerequisites(): boolean {
  section('Prerequisites');
  let allGood = true;

  // Node version
  const nv = nodeVersion();
  const major = parseInt(nv.slice(1), 10);
  if (major >= 20) {
    ok(`Node.js ${nv}`);
  } else {
    fail(`Node.js ${nv} — need v20+`);
    allGood = false;
  }

  // Docker or Apple Container
  const hasDocker = checkCommand('docker');
  const hasAppleContainer = checkCommand('container');
  if (hasDocker) {
    ok('Docker detected');
  } else if (hasAppleContainer) {
    ok('Apple Container detected');
  } else {
    warn('No container runtime found (Docker or Apple Container)');
    info('Agent containers require Docker or Apple Container to run');
    info('Install Docker: https://docs.docker.com/get-docker/');
    info('BDR Brain and web UI will still work without containers');
  }

  // Check if .env exists
  if (fs.existsSync('.env')) {
    ok('.env file exists');
  } else {
    info('.env will be created');
  }

  return allGood || true; // non-fatal — container is optional for initial setup
}

// ── .env manager ─────────────────────────────────────────────────────────────

function readEnv(): Record<string, string> {
  const envPath = path.resolve('.env');
  if (!fs.existsSync(envPath)) return {};
  const content = fs.readFileSync(envPath, 'utf-8');
  const result: Record<string, string> = {};
  for (const line of content.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eqIdx = trimmed.indexOf('=');
    if (eqIdx === -1) continue;
    const key = trimmed.slice(0, eqIdx).trim();
    const val = trimmed.slice(eqIdx + 1).trim().replace(/^["']|["']$/g, '');
    result[key] = val;
  }
  return result;
}

function writeEnv(vars: Record<string, string>): void {
  const existing = readEnv();
  const merged = { ...existing, ...vars };

  const sections: string[] = [
    '# BDRclaw Environment Configuration',
    '# Generated by: npm run wizard',
    `# Updated: ${new Date().toISOString()}`,
    '',
    '# ── Core ──────────────────────────────────────────────────────────',
    `ANTHROPIC_API_KEY=${merged.ANTHROPIC_API_KEY ?? ''}`,
    `BDR_COMPANY_NAME=${merged.BDR_COMPANY_NAME ?? ''}`,
    `BDR_CLOSER_EMAIL=${merged.BDR_CLOSER_EMAIL ?? ''}`,
    `BDR_WEB_PORT=${merged.BDR_WEB_PORT ?? '3000'}`,
    `BDR_BRAIN_HOUR=${merged.BDR_BRAIN_HOUR ?? '6'}`,
    `ASSISTANT_NAME=${merged.ASSISTANT_NAME ?? 'BDR'}`,
    '',
    '# ── Email Accounts ────────────────────────────────────────────────',
  ];

  // Gmail accounts
  for (let i = 1; i <= 3; i++) {
    const emailKey = `GMAIL_ACCOUNT_${i}_EMAIL`;
    const passKey = `GMAIL_ACCOUNT_${i}_APP_PASSWORD`;
    if (merged[emailKey]) {
      sections.push(`${emailKey}=${merged[emailKey]}`);
      sections.push(`${passKey}=${merged[passKey] ?? ''}`);
    }
  }

  // Outlook accounts
  for (let i = 1; i <= 3; i++) {
    const emailKey = `OUTLOOK_ACCOUNT_${i}_EMAIL`;
    const passKey = `OUTLOOK_ACCOUNT_${i}_PASSWORD`;
    if (merged[emailKey]) {
      sections.push(`${emailKey}=${merged[emailKey]}`);
      sections.push(`${passKey}=${merged[passKey] ?? ''}`);
    }
  }

  sections.push('', '# ── LinkedIn Accounts ────────────────────────────────────────────');
  for (let i = 1; i <= 3; i++) {
    const emailKey = `LINKEDIN_ACCOUNT_${i}_EMAIL`;
    const passKey = `LINKEDIN_ACCOUNT_${i}_PASSWORD`;
    if (merged[emailKey]) {
      sections.push(`${emailKey}=${merged[emailKey]}`);
      sections.push(`${passKey}=${merged[passKey] ?? ''}`);
    }
  }

  sections.push('', '# ── CRM ──────────────────────────────────────────────────────────');
  if (merged.HUBSPOT_API_KEY) sections.push(`HUBSPOT_API_KEY=${merged.HUBSPOT_API_KEY}`);
  if (merged.SALESFORCE_CLIENT_ID) {
    sections.push(`SALESFORCE_CLIENT_ID=${merged.SALESFORCE_CLIENT_ID}`);
    sections.push(`SALESFORCE_CLIENT_SECRET=${merged.SALESFORCE_CLIENT_SECRET ?? ''}`);
    sections.push(`SALESFORCE_INSTANCE_URL=${merged.SALESFORCE_INSTANCE_URL ?? ''}`);
  }
  if (merged.MONDAY_API_KEY) sections.push(`MONDAY_API_KEY=${merged.MONDAY_API_KEY}`);

  sections.push('', '# ── Timezone ─────────────────────────────────────────────────────');
  sections.push(`TZ=${merged.TZ ?? 'America/New_York'}`);

  fs.writeFileSync('.env', sections.join('\n') + '\n', 'utf-8');
}

// ── Directory bootstrap ───────────────────────────────────────────────────────

function bootstrapDirectories(): void {
  const dirs = [
    'prospects',
    'imports',
    'store',
    'groups/main',
    'groups/gmail',
    'groups/linkedin',
    'logs',
  ];
  for (const dir of dirs) {
    fs.mkdirSync(dir, { recursive: true });
  }
  ok('Directory structure created');

  // Create imports README
  const importsReadme = path.join('imports', 'README.md');
  if (!fs.existsSync(importsReadme)) {
    fs.writeFileSync(importsReadme,
      '# Imports\n\nDrop CSV or Excel files here to import leads.\n\nRequired columns: name, company, title, email (optional), linkedin_url (optional)\n',
      'utf-8',
    );
  }
}

// ── Account seeding ───────────────────────────────────────────────────────────

async function seedAccounts(env: Record<string, string>): Promise<void> {
  // Dynamically import bdr-db to seed accounts after init
  try {
    const { initBDRDatabase, upsertAccount } = await import('../src/bdr-db.js');
    initBDRDatabase();

    const now = new Date().toISOString();

    // Gmail accounts
    for (let i = 1; i <= 3; i++) {
      const email = env[`GMAIL_ACCOUNT_${i}_EMAIL`];
      if (!email) continue;
      upsertAccount({
        id: `gmail-${i}`,
        type: 'gmail',
        name: `Gmail ${i}`,
        email,
        credentials_key: `GMAIL_ACCOUNT_${i}`,
        status: 'active',
        daily_send_limit: 50,
        sends_today: 0,
        created_at: now,
      });
      ok(`Seeded account: Gmail ${i} (${email})`);
    }

    // LinkedIn accounts
    for (let i = 1; i <= 3; i++) {
      const email = env[`LINKEDIN_ACCOUNT_${i}_EMAIL`];
      if (!email) continue;
      upsertAccount({
        id: `linkedin-${i}`,
        type: 'linkedin',
        name: `LinkedIn ${i}`,
        email,
        credentials_key: `LINKEDIN_ACCOUNT_${i}`,
        status: 'unconfigured', // needs /add-linkedin skill
        daily_send_limit: 20,
        sends_today: 0,
        created_at: now,
      });
      ok(`Seeded account: LinkedIn ${i} (${email})`);
    }
  } catch (err) {
    warn('Could not seed accounts to DB (run npm install first)');
    info(String(err));
  }
}

// ── Main wizard ───────────────────────────────────────────────────────────────

async function main(): Promise<void> {
  // Header
  nl();
  print(`${C.bold}${C.blue}╔══════════════════════════════════════════════╗${C.reset}`);
  print(`${C.bold}${C.blue}║  🦞  BDRclaw Setup Wizard                   ║${C.reset}`);
  print(`${C.bold}${C.blue}║      AI-native BDR team — first-time setup   ║${C.reset}`);
  print(`${C.bold}${C.blue}╚══════════════════════════════════════════════╝${C.reset}`);
  nl();
  print(m(`  This wizard configures BDRclaw for your environment.`));
  print(m(`  You can re-run it any time to add accounts or update settings.`));
  nl();

  // ── Step 1: Prerequisites ──────────────────────────────────────────────────
  checkPrerequisites();

  // ── Step 2: Anthropic API key ──────────────────────────────────────────────
  section('Anthropic API Key');
  const existing = readEnv();
  let anthropicKey = existing.ANTHROPIC_API_KEY ?? '';
  if (anthropicKey) {
    ok(`API key already configured (${anthropicKey.slice(0, 10)}...)`);
    const change = await confirm('Change it?', false);
    if (change) anthropicKey = '';
  }
  if (!anthropicKey) {
    print(`  Get your API key at ${c('https://console.anthropic.com')} → API Keys`);
    nl();
    anthropicKey = await ask(`  ${b('Anthropic API key:')} `);
    if (!anthropicKey) {
      warn('Skipping — BDRclaw needs an Anthropic API key to run agents');
    }
  }

  // ── Step 3: Company info ───────────────────────────────────────────────────
  section('Your Company');
  const companyName = await ask(`  ${b('Company name:')} ${m('(used in outreach emails)')} `);
  const closerEmail = await ask(`  ${b('Closer / owner email:')} ${m('(receives hot lead alerts)')} `);
  const timezone = await ask(`  ${b('Timezone:')} ${m('[America/New_York]')} `) || 'America/New_York';

  // ── Step 4: Brain schedule ─────────────────────────────────────────────────
  section('BDR Brain Schedule');
  print(`  The BDR Brain reviews your pipeline daily and queues actions.`);
  nl();
  const brainHour = await ask(`  ${b('Run brain at hour (0-23):')} ${m('[6]')} `) || '6';
  ok(`Brain scheduled for ${brainHour}:00 daily`);

  // ── Step 5: Email accounts ─────────────────────────────────────────────────
  section('Email Accounts');
  print(`  BDRclaw can use up to 3 Gmail or Outlook accounts for outreach.`);
  print(`  ${m('Gmail: enable 2FA and create an App Password at myaccount.google.com → Security')}`);
  print(`  ${m('Outlook: use your email + app password from account.microsoft.com')}`);
  nl();

  const emailAccounts: Array<{ email: string; password: string; type: 'gmail' | 'outlook' }> = [];
  const numEmail = parseInt(await ask(`  ${b('How many email accounts?')} ${m('[1]')} `) || '1', 10);

  for (let i = 1; i <= Math.min(numEmail, 3); i++) {
    nl();
    print(`  ${b(`Email account ${i}:`)}`);
    const emailAddr = await ask(`    Email address: `);
    if (!emailAddr) break;
    const isGmail = emailAddr.toLowerCase().includes('gmail') ||
      (await confirm(`    Is this a Gmail account?`));
    const appPass = await ask(`    App password: `);
    emailAccounts.push({
      email: emailAddr,
      password: appPass,
      type: isGmail ? 'gmail' : 'outlook',
    });
    ok(`Account ${i}: ${emailAddr} (${isGmail ? 'Gmail' : 'Outlook'})`);
  }

  // ── Step 6: LinkedIn accounts ──────────────────────────────────────────────
  section('LinkedIn Accounts');
  print(`  LinkedIn accounts for connection requests and DM sequences.`);
  print(`  ${m('Note: /add-linkedin skill is required to activate LinkedIn outreach.')}`);
  nl();

  const linkedinAccounts: Array<{ email: string; password: string }> = [];
  const wantsLinkedIn = await confirm(`  Configure LinkedIn account(s)?`, false);

  if (wantsLinkedIn) {
    const numLI = parseInt(await ask(`  ${b('How many LinkedIn accounts?')} ${m('[1]')} `) || '1', 10);
    for (let i = 1; i <= Math.min(numLI, 3); i++) {
      nl();
      print(`  ${b(`LinkedIn account ${i}:`)}`);
      const liEmail = await ask(`    LinkedIn email: `);
      if (!liEmail) break;
      const liPass = await ask(`    LinkedIn password: `);
      linkedinAccounts.push({ email: liEmail, password: liPass });
      ok(`Account ${i}: ${liEmail}`);
    }
  }

  // ── Step 7: CRM ────────────────────────────────────────────────────────────
  section('CRM Integration (optional)');
  print(`  BDRclaw can sync to HubSpot, Salesforce, or Monday.com.`);
  print(`  ${m('CRM skills need to be installed separately with /add-hubspot etc.')}`);
  nl();

  let hubspotKey = '';
  const wantsHubspot = await confirm(`  Configure HubSpot?`, false);
  if (wantsHubspot) {
    hubspotKey = await ask(`    HubSpot API key: ${m('(Settings → Integrations → API Key)')} `);
  }

  let mondayKey = '';
  const wantsMonday = await confirm(`  Configure Monday.com?`, false);
  if (wantsMonday) {
    mondayKey = await ask(`    Monday.com API token: ${m('(Profile → Developers → API)')} `);
  }

  // ── Step 8: Web UI port ────────────────────────────────────────────────────
  section('Web Dashboard');
  const webPort = await ask(`  ${b('Dashboard port:')} ${m('[3000]')} `) || '3000';
  ok(`Dashboard will be available at ${c(`http://127.0.0.1:${webPort}`)}`);

  // ── Write .env ─────────────────────────────────────────────────────────────
  section('Writing Configuration');

  const envVars: Record<string, string> = {
    ANTHROPIC_API_KEY: anthropicKey,
    BDR_COMPANY_NAME: companyName,
    BDR_CLOSER_EMAIL: closerEmail,
    BDR_WEB_PORT: webPort,
    BDR_BRAIN_HOUR: brainHour,
    ASSISTANT_NAME: 'BDR',
    TZ: timezone,
  };

  emailAccounts.forEach((acc, idx) => {
    const n = idx + 1;
    const prefix = acc.type === 'gmail' ? 'GMAIL' : 'OUTLOOK';
    envVars[`${prefix}_ACCOUNT_${n}_EMAIL`] = acc.email;
    envVars[`${prefix}_ACCOUNT_${n}_APP_PASSWORD`] = acc.password;
  });

  linkedinAccounts.forEach((acc, idx) => {
    const n = idx + 1;
    envVars[`LINKEDIN_ACCOUNT_${n}_EMAIL`] = acc.email;
    envVars[`LINKEDIN_ACCOUNT_${n}_PASSWORD`] = acc.password;
  });

  if (hubspotKey) envVars.HUBSPOT_API_KEY = hubspotKey;
  if (mondayKey) envVars.MONDAY_API_KEY = mondayKey;

  writeEnv(envVars);
  ok('.env written');

  // ── Bootstrap directories ──────────────────────────────────────────────────
  bootstrapDirectories();

  // ── Seed accounts to DB ────────────────────────────────────────────────────
  await seedAccounts(envVars);

  // ── Install deps if needed ─────────────────────────────────────────────────
  if (!fs.existsSync('node_modules')) {
    section('Installing Dependencies');
    print('  Running npm install...');
    try {
      execSync('npm install', { stdio: 'inherit' });
      ok('Dependencies installed');
    } catch {
      warn('npm install failed — run it manually');
    }
  }

  // ── Done ───────────────────────────────────────────────────────────────────
  nl();
  print(`${C.bold}${C.green}╔══════════════════════════════════════════════╗${C.reset}`);
  print(`${C.bold}${C.green}║  ✓  BDRclaw is configured!                  ║${C.reset}`);
  print(`${C.bold}${C.green}╚══════════════════════════════════════════════╝${C.reset}`);
  nl();
  print(`  ${b('Next steps:')}`);
  nl();
  print(`  1. ${c('npm run dev')}        — start BDRclaw daemon`);
  print(`  2. ${c(`open http://127.0.0.1:${webPort}`)} — view dashboard`);
  print(`  3. Install channel skills:`);
  print(`     ${m('/add-gmail')}     — activate email outreach`);
  print(`     ${m('/add-linkedin')}  — activate LinkedIn outreach`);
  print(`     ${m('/add-hubspot')}   — activate CRM sync`);
  nl();
  print(`  Drop CSV files in ${c('imports/')} to import leads.`);
  print(`  The BDR Brain runs daily at ${brainHour}:00 ${timezone}.`);
  nl();

  rl.close();
}

main().catch((err) => {
  console.error(r('\nSetup failed: ') + String(err));
  rl.close();
  process.exit(1);
});
